name: Build and Package on Tag

on:
  push:
    branches: [ "automated-releases" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build with PyInstaller
      run: pyinstaller times.spec -y

    - name: Package with Inno Setup
      run: "C:\\Program Files (x86)\\Inno Setup 6\\iscc.exe times.iss"