name: Build and Package on Tag

on:
  push:
    branches: [ "automated-releases" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: update version
      run: |
        sed -i 's/version = \"replace me for real version\"/version = \"$GITHUB_REF_NAME\"/' times.py
        sed -i 's/MyAppVersion \"replace me for real version\"/MyAppVersion \"$GITHUB_REF_NAME\"/' times.iss

    - name: Build with PyInstaller
      run: pyinstaller times.spec -y

    - name: Package with Inno Setup
      uses: Minionguyjpro/Inno-Setup-Action@v1.2.5
      with:
        path: times.iss
        options: /O+